AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

# -------------------------------------------------------------
#  パラメータ定義
#   - codebuild\envs\dev.yml参照
#    - AppId:アプリケーションID
#    - EnvId:環境
# -------------------------------------------------------------
Parameters:
  AppId:
    Description: An application ID that is prefixed to resource names
    Type: String

  EnvId:
    Description: An environment ID that is prefixed to resource names
    Type: String

Mappings:
  ScheduleExpression:
    dev:
      Start: "cron(30 8 ? * MON-FRI *)"
      Stop: "cron(00 18 ? * * *)"
      State: ENABLED

# -------------------------------------------------------------
#  リソース定義
# -------------------------------------------------------------
Resources:

  # -------------------------------------------------------------
  #  EventBridge
  # -------------------------------------------------------------
  EcsStartFunctionSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name:
        !Join
          - '-'
          - - 'event-schedule'
            - !Sub '${AppId}'
            - !Sub '${EnvId}'
            - 'ecs-start'
      Description: "ECS START"
      ScheduleExpression: !FindInMap [ScheduleExpression, !Ref EnvId, Start]
      ScheduleExpressionTimezone: "Asia/Tokyo"
      State: !FindInMap [ScheduleExpression, !Ref EnvId, State]
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: {"Fn::ImportValue": !Sub "${AppId}-${EnvId}-ecs-start-arn"}
        RoleArn: {"Fn::ImportValue": !Sub "${AppId}-${EnvId}-ecs-start-stop-role-arn"}
        RetryPolicy:
            {
                MaximumEventAgeInSeconds: 60,
                MaximumRetryAttempts: 5
            }
        Input: !Sub |-
            {
                "ECS_CLUSTER_NAME": "${AppId}-${EnvId}-ecs-cluster",
                "ECS_SERVICE_NAME": "${AppId}-${EnvId}-webapp-ecs-service"
            }

  EcsStopFunctionSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name:
        !Join
          - '-'
          - - 'event-schedule'
            - !Sub '${AppId}'
            - !Sub '${EnvId}'
            - 'ecs-stop'
      Description: "ECS STOP"
      ScheduleExpression: !FindInMap [ScheduleExpression, !Ref EnvId, Stop]
      ScheduleExpressionTimezone: "Asia/Tokyo"
      State: !FindInMap [ScheduleExpression, !Ref EnvId, State]
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: {"Fn::ImportValue": !Sub "${AppId}-${EnvId}-ecs-stop-arn"}
        RoleArn: {"Fn::ImportValue": !Sub "${AppId}-${EnvId}-ecs-start-stop-role-arn"}
        RetryPolicy:
            {
                MaximumEventAgeInSeconds: 60,
                MaximumRetryAttempts: 5
            }
        Input: !Sub |-
            {
                "ECS_CLUSTER_NAME": "${AppId}-${EnvId}-ecs-cluster",
                "ECS_SERVICE_NAME": "${AppId}-${EnvId}-webapp-ecs-service"
            }